### ISSUE TITLE
"the docs" link broken in README.md

### ISSUE THREAD

**Issue by strk** [drone-plugins/drone-cache#10]
Subject says it all, the target link for "the docs" anchor is a 404 from https://github.com/drone-plugins/drone-cache

**Comment by tboerger** [comment]
Because it doesn't have any documentation.

**Comment by qrpike** [comment]
Does this work the same way in 0.5 as it did in 0.4 ?

**Comment by bradrydzewski** [comment]
This plugin is not being ported to 0.5 for reasons discussed in https://github.com/drone/drone/issues/1617

There is a community-supported plugin that emulates the behavior that you can use with 0.5
http://plugins.drone.io/drillster/drone-volume-cache/
