### ISSUE TITLE
Unable to rebuild cache, exit status 1

### ISSUE THREAD

**Issue by wolfgang42** [drone-plugins/drone-cache#2]
If the cache configuration in `.drone.yml` contains a path which does not exist, a rather cryptic error message is emitted:

```
Building cache this_folder_does_not_exist
Unable to rebuild cache for this_folder_does_not_exist. exit status 1
```

In my case I modified the file to work with Drone 0.4 and didn't notice that the new cache plugin could only cache folders in the build workspace; I was trying to cache `/root/.npm`.

It seems like it would be helpful to write in a check to make sure the folder being cached actually exists in the build workspace, so a better error message can be printed. Something like

```
Unable to rebuild cache for this_folder_does_not_exist: the folder does not exist in the build workspace.
```

**Comment by bradrydzewski** [comment]
done! thanks for the suggestion

reference https://github.com/drone-plugins/drone-cache/commit/d7c97471381cbebd568b44385882b1b45e94c8c2

**Comment by bradrydzewski** [comment]
as a side note, what is the command or notation for overriding the default global `/root/.npm` location?

**Comment by wolfgang42** [comment]
I had to look this up: http://stackoverflow.com/questions/14836053/how-can-i-change-the-cache-path-for-npm-or-completely-disable-the-cache-on-win says it's `npm config set cache [location] [--global]`.

I don't recall why I was caching `/root/.npm` instead of `node_modules`.
