### ISSUE TITLE
Doesn't generate cache after build is green

### ISSUE THREAD

**Issue by orlando** [drone-plugins/drone-cache#8]
My drone instance stopped building cache after it finish a build green. It happens just like this log http://drone.hoppinger.com/hoppinger/faker/5

There's some cached files in /var/lib/drone, but when the build starts, it doesn't use this. All the workers are running in the same machine.

Also, when a build is green, sometimes it doesn't cache the results:

```
Drone Cache Plugin built from 96d0472
Building cache .git
Building cache node_modules
```

Sometimes just outputs

```
Drone Cache Plugin built from 96d0472
```

I don't have idea what can be happening. I'm almost sure this is something related to my env, but if you have any suggestion where to start looking at that would be great.

Thanks!

**Comment by bradrydzewski** [comment]
Is this for a pull request? Pull requests have read-only access to the cache

**Comment by orlando** [comment]
Yes is for a pull request, ok so pull request don't generate cache then (I need to enable build triggering with push hooks then).

btw why is that? (Pull requests don't write cache)

In my case, pull requests also fail to read from cache.

```
Drone Cache Plugin built from 96d0472
Restoring cache .git
Unable to restore .git. Cache does not exist
Restoring cache from master branch
Unable to restore .git from master branch.
Restoring cache node_modules
Unable to restore node_modules. Cache does not exist
Restoring cache from master branch
Unable to restore node_modules from master branch.
```

**Comment by bradrydzewski** [comment]
it is for security reasons. a malicious pull request to override data in the cache and compromise your build environment, inject malicious code, etc

**Comment by orlando** [comment]
Cool, thanks for the input @bradrydzewski.

Any idea why pull requests fail to read from cache?

**Comment by bitemyapp** [comment]
@bradrydzewski is there a way to disable this limitation when you have a private repo which cannot be PR'd out of the blue?

**Comment by donny-dont** [comment]
@bitemyapp the behavior is changing for 0.5 https://github.com/drone/drone/issues/1617. If something there is suspect to you feel free to chime in. This repo will be deprecated after a 0.5 release.
